import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Notes App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1 className='text-red-300 text-2xl'>Let's Make Notes App</h1>
    </div>
  )
}
